# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://staff.washington.edu/ivanoats
title: Ivan Storck at University of Washington
subtitle: Notes on coding Ruby, Rails, Teaching, and Entrepreneurship
author: Ivan Storck
simple_search: http://google.com/search
description: Notes on coding Ruby, Rails, Teaching, and Entrepreneurship

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /ivanoats/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /ivanoats
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/ivanoats
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/gravatar.html, asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html, asides/stackoverflow.html, asides/coderwall.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: ivanoats
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: ivanoats
twitter_tweet_count: 6
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 117410083815784099792
googleplus_hidden: false

# Delicious
delicious_user: ivanoats
delicious_count: 3

# Disqus Comments
disqus_short_name: ivanoatsuw

# Google Analytics
google_analytics_tracking_id: UA-3487613-5

# Facebook Like
facebook_like: true

# StackOverflow
stackoverflow_user_name: ivanoats
stackoverflow_user_id: 394133

# Coderwall
coderwall_user: ivanoats

# Gravatar
gravatar_hash: 3dd41cc916f9ad4c68b1b0fa81c7b273
